// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this StatusPageService.
func (mg *StatusPageService) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.StatusPageID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.StatusPageIDRef,
		Selector:     mg.Spec.ForProvider.StatusPageIDSelector,
		To: reference.To{
			List:    &StatusPageList{},
			Managed: &StatusPage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.StatusPageID")
	}
	mg.Spec.ForProvider.StatusPageID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.StatusPageIDRef = rsp.ResolvedReference

	return nil
}
