// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PageServiceInitParameters struct {

	// (String) The name of the service.
	// The name of the service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PageServiceObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the service.
	// The name of the service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PageServiceParameters struct {

	// (String) The name of the service.
	// The name of the service.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// PageServiceSpec defines the desired state of PageService
type PageServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PageServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PageServiceInitParameters `json:"initProvider,omitempty"`
}

// PageServiceStatus defines the observed state of PageService.
type PageServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PageServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PageService is the Schema for the PageServices API. Status page services represent functional pieces of your application or website, such as landing page, API, support portal etc.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,checkly}
type PageService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PageServiceSpec   `json:"spec"`
	Status PageServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PageServiceList contains a list of PageServices
type PageServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PageService `json:"items"`
}

// Repository type metadata.
var (
	PageService_Kind             = "PageService"
	PageService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PageService_Kind}.String()
	PageService_KindAPIVersion   = PageService_Kind + "." + CRDGroupVersion.String()
	PageService_GroupVersionKind = CRDGroupVersion.WithKind(PageService_Kind)
)

func init() {
	SchemeBuilder.Register(&PageService{}, &PageServiceList{})
}
