// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SnippetInitParameters struct {

	// (String) The name of the snippet
	// The name of the snippet
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	// Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type SnippetObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the snippet
	// The name of the snippet
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	// Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type SnippetParameters struct {

	// (String) The name of the snippet
	// The name of the snippet
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	// Your Node.js code that interacts with the API check lifecycle, or functions as a partial for browser checks.
	// +kubebuilder:validation:Optional
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

// SnippetSpec defines the desired state of Snippet
type SnippetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SnippetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SnippetInitParameters `json:"initProvider,omitempty"`
}

// SnippetStatus defines the observed state of Snippet.
type SnippetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SnippetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Snippet is the Schema for the Snippets API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,checkly}
type Snippet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.script) || (has(self.initProvider) && has(self.initProvider.script))",message="spec.forProvider.script is a required parameter"
	Spec   SnippetSpec   `json:"spec"`
	Status SnippetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SnippetList contains a list of Snippets
type SnippetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Snippet `json:"items"`
}

// Repository type metadata.
var (
	Snippet_Kind             = "Snippet"
	Snippet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Snippet_Kind}.String()
	Snippet_KindAPIVersion   = Snippet_Kind + "." + CRDGroupVersion.String()
	Snippet_GroupVersionKind = CRDGroupVersion.WithKind(Snippet_Kind)
)

func init() {
	SchemeBuilder.Register(&Snippet{}, &SnippetList{})
}
