// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CheckInitParameters struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type CheckObservation struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type CheckParameters struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	// +kubebuilder:validation:Optional
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	// +kubebuilder:validation:Optional
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// CheckSpec defines the desired state of Check
type CheckSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CheckParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CheckInitParameters `json:"initProvider,omitempty"`
}

// CheckStatus defines the observed state of Check.
type CheckStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CheckObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Check is the Schema for the Checks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,checkly}
type Check struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.checkId) || (has(self.initProvider) && has(self.initProvider.checkId))",message="spec.forProvider.checkId is a required parameter"
	Spec   CheckSpec   `json:"spec"`
	Status CheckStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CheckList contains a list of Checks
type CheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Check `json:"items"`
}

// Repository type metadata.
var (
	Check_Kind             = "Check"
	Check_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Check_Kind}.String()
	Check_KindAPIVersion   = Check_Kind + "." + CRDGroupVersion.String()
	Check_GroupVersionKind = CRDGroupVersion.WithKind(Check_Kind)
)

func init() {
	SchemeBuilder.Register(&Check{}, &CheckList{})
}
