// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TriggerCheckInitParameters struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/cluster/checks/v1alpha1.Check
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// Reference to a Check in checks to populate checkId.
	// +kubebuilder:validation:Optional
	CheckIDRef *v1.Reference `json:"checkIdRef,omitempty" tf:"-"`

	// Selector for a Check in checks to populate checkId.
	// +kubebuilder:validation:Optional
	CheckIDSelector *v1.Selector `json:"checkIdSelector,omitempty" tf:"-"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TriggerCheckObservation struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TriggerCheckParameters struct {

	// (String) The id of the check that you want to attach the trigger to.
	// The id of the check that you want to attach the trigger to.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/cluster/checks/v1alpha1.Check
	// +kubebuilder:validation:Optional
	CheckID *string `json:"checkId,omitempty" tf:"check_id,omitempty"`

	// Reference to a Check in checks to populate checkId.
	// +kubebuilder:validation:Optional
	CheckIDRef *v1.Reference `json:"checkIdRef,omitempty" tf:"-"`

	// Selector for a Check in checks to populate checkId.
	// +kubebuilder:validation:Optional
	CheckIDSelector *v1.Selector `json:"checkIdSelector,omitempty" tf:"-"`

	// (String) The token value created to trigger the check
	// The token value created to trigger the check
	// +kubebuilder:validation:Optional
	Token *string `json:"token,omitempty" tf:"token,omitempty"`

	// (String) The request URL to trigger the check run.
	// The request URL to trigger the check run.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// TriggerCheckSpec defines the desired state of TriggerCheck
type TriggerCheckSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TriggerCheckParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TriggerCheckInitParameters `json:"initProvider,omitempty"`
}

// TriggerCheckStatus defines the observed state of TriggerCheck.
type TriggerCheckStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TriggerCheckObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TriggerCheck is the Schema for the TriggerChecks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,checkly}
type TriggerCheck struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TriggerCheckSpec   `json:"spec"`
	Status            TriggerCheckStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TriggerCheckList contains a list of TriggerChecks
type TriggerCheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TriggerCheck `json:"items"`
}

// Repository type metadata.
var (
	TriggerCheck_Kind             = "TriggerCheck"
	TriggerCheck_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TriggerCheck_Kind}.String()
	TriggerCheck_KindAPIVersion   = TriggerCheck_Kind + "." + CRDGroupVersion.String()
	TriggerCheck_GroupVersionKind = CRDGroupVersion.WithKind(TriggerCheck_Kind)
)

func init() {
	SchemeBuilder.Register(&TriggerCheck{}, &TriggerCheckList{})
}
