apiVersion: statuspage.checkly.crossplane.io/v1alpha1
kind: StatusPageService
metadata:
  annotations:
    meta.upbound.io/example-id: statuspage/v1alpha1/statuspageservice
  labels:
    testing.upbound.io/example-name: backend
  name: backend
spec:
  forProvider:
    name: Backend
