apiVersion: statuspage.checkly.crossplane.io/v1alpha1
kind: StatusPage
metadata:
  annotations:
    meta.upbound.io/example-id: statuspage/v1alpha1/statuspage
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    card:
    - name: Services
      serviceAttachment:
      - serviceId: ${checkly_status_page_service.api.id}
      - serviceId: ${checkly_status_page_service.database.id}
    defaultTheme: DARK
    name: Example Application
    url: my-example-status-page

---

apiVersion: statuspage.checkly.crossplane.io/v1alpha1
kind: StatusPageService
metadata:
  annotations:
    meta.upbound.io/example-id: statuspage/v1alpha1/statuspage
  labels:
    testing.upbound.io/example-name: api
  name: api
spec:
  forProvider:
    name: API

---

apiVersion: statuspage.checkly.crossplane.io/v1alpha1
kind: StatusPageService
metadata:
  annotations:
    meta.upbound.io/example-id: statuspage/v1alpha1/statuspage
  labels:
    testing.upbound.io/example-name: database
  name: database
spec:
  forProvider:
    name: Database
