apiVersion: infra.checkly.crossplane.io/v1alpha1
kind: PrivateLocation
metadata:
  annotations:
    meta.upbound.io/example-id: infra/v1alpha1/privatelocation
  labels:
    testing.upbound.io/example-name: location
  name: location
spec:
  forProvider:
    name: New Private Location
    slugName: new-private-location
