// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Check) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckGroupV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DNSMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Heartbeat) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HeartbeatMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ICMPMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PlaywrightCheckSuite) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PlaywrightCodeBundle) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPCheck) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *URLMonitor) Hub() {}
