// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HeartbeatAlertChannelSubscriptionInitParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/cluster/alerts/v1alpha1.AlertChannel
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.Reference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.Selector `json:"channelIdSelector,omitempty" tf:"-"`
}

type HeartbeatAlertChannelSubscriptionObservation struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`
}

type HeartbeatAlertChannelSubscriptionParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/cluster/alerts/v1alpha1.AlertChannel
	// +kubebuilder:validation:Optional
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.Reference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.Selector `json:"channelIdSelector,omitempty" tf:"-"`
}

type HeartbeatAlertSettingsInitParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []HeartbeatAlertSettingsParallelRunFailureThresholdInitParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []HeartbeatAlertSettingsRemindersInitParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []HeartbeatAlertSettingsRunBasedEscalationInitParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// (Block Set, Deprecated) (see below for nested schema)
	SSLCertificates []HeartbeatAlertSettingsSSLCertificatesInitParameters `json:"sslCertificates,omitempty" tf:"ssl_certificates,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []HeartbeatAlertSettingsTimeBasedEscalationInitParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type HeartbeatAlertSettingsObservation struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []HeartbeatAlertSettingsParallelRunFailureThresholdObservation `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []HeartbeatAlertSettingsRemindersObservation `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []HeartbeatAlertSettingsRunBasedEscalationObservation `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// (Block Set, Deprecated) (see below for nested schema)
	SSLCertificates []HeartbeatAlertSettingsSSLCertificatesObservation `json:"sslCertificates,omitempty" tf:"ssl_certificates,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []HeartbeatAlertSettingsTimeBasedEscalationObservation `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type HeartbeatAlertSettingsParallelRunFailureThresholdInitParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type HeartbeatAlertSettingsParallelRunFailureThresholdObservation struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type HeartbeatAlertSettingsParallelRunFailureThresholdParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	// +kubebuilder:validation:Optional
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type HeartbeatAlertSettingsParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	// +kubebuilder:validation:Optional
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	// +kubebuilder:validation:Optional
	ParallelRunFailureThreshold []HeartbeatAlertSettingsParallelRunFailureThresholdParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	// +kubebuilder:validation:Optional
	Reminders []HeartbeatAlertSettingsRemindersParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	// +kubebuilder:validation:Optional
	RunBasedEscalation []HeartbeatAlertSettingsRunBasedEscalationParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// (Block Set, Deprecated) (see below for nested schema)
	// +kubebuilder:validation:Optional
	SSLCertificates []HeartbeatAlertSettingsSSLCertificatesParameters `json:"sslCertificates,omitempty" tf:"ssl_certificates,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	// +kubebuilder:validation:Optional
	TimeBasedEscalation []HeartbeatAlertSettingsTimeBasedEscalationParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type HeartbeatAlertSettingsRemindersInitParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type HeartbeatAlertSettingsRemindersObservation struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type HeartbeatAlertSettingsRemindersParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type HeartbeatAlertSettingsRunBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type HeartbeatAlertSettingsRunBasedEscalationObservation struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type HeartbeatAlertSettingsRunBasedEscalationParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	// +kubebuilder:validation:Optional
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type HeartbeatAlertSettingsSSLCertificatesInitParameters struct {

	// (Number) No longer available.
	// No longer available.
	AlertThreshold *float64 `json:"alertThreshold,omitempty" tf:"alert_threshold,omitempty"`

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// No longer available.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type HeartbeatAlertSettingsSSLCertificatesObservation struct {

	// (Number) No longer available.
	// No longer available.
	AlertThreshold *float64 `json:"alertThreshold,omitempty" tf:"alert_threshold,omitempty"`

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// No longer available.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type HeartbeatAlertSettingsSSLCertificatesParameters struct {

	// (Number) No longer available.
	// No longer available.
	// +kubebuilder:validation:Optional
	AlertThreshold *float64 `json:"alertThreshold,omitempty" tf:"alert_threshold,omitempty"`

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// No longer available.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type HeartbeatAlertSettingsTimeBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type HeartbeatAlertSettingsTimeBasedEscalationObservation struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type HeartbeatAlertSettingsTimeBasedEscalationParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type HeartbeatHeartbeatInitParameters struct {

	// (Number) How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	// How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	Grace *float64 `json:"grace,omitempty" tf:"grace,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	GraceUnit *string `json:"graceUnit,omitempty" tf:"grace_unit,omitempty"`

	// (Number) How often you expect a ping to the ping URL.
	// How often you expect a ping to the ping URL.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// (String) Custom token to generate your ping URL. Checkly will expect a ping to https://ping.checklyhq.com/[PING_TOKEN].
	// Custom token to generate your ping URL. Checkly will expect a ping to `https://ping.checklyhq.com/[PING_TOKEN]`.
	PingToken *string `json:"pingToken,omitempty" tf:"ping_token,omitempty"`
}

type HeartbeatHeartbeatObservation struct {

	// (Number) How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	// How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	Grace *float64 `json:"grace,omitempty" tf:"grace,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	GraceUnit *string `json:"graceUnit,omitempty" tf:"grace_unit,omitempty"`

	// (Number) How often you expect a ping to the ping URL.
	// How often you expect a ping to the ping URL.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// (String) Custom token to generate your ping URL. Checkly will expect a ping to https://ping.checklyhq.com/[PING_TOKEN].
	// Custom token to generate your ping URL. Checkly will expect a ping to `https://ping.checklyhq.com/[PING_TOKEN]`.
	PingToken *string `json:"pingToken,omitempty" tf:"ping_token,omitempty"`
}

type HeartbeatHeartbeatParameters struct {

	// (Number) How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	// How long Checkly should wait before triggering any alerts when a ping does not arrive within the set period.
	// +kubebuilder:validation:Optional
	Grace *float64 `json:"grace" tf:"grace,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	// +kubebuilder:validation:Optional
	GraceUnit *string `json:"graceUnit" tf:"grace_unit,omitempty"`

	// (Number) How often you expect a ping to the ping URL.
	// How often you expect a ping to the ping URL.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period" tf:"period,omitempty"`

	// (String) Possible values seconds, minutes, hours and days.
	// Possible values `seconds`, `minutes`, `hours` and `days`.
	// +kubebuilder:validation:Optional
	PeriodUnit *string `json:"periodUnit" tf:"period_unit,omitempty"`

	// (String) Custom token to generate your ping URL. Checkly will expect a ping to https://ping.checklyhq.com/[PING_TOKEN].
	// Custom token to generate your ping URL. Checkly will expect a ping to `https://ping.checklyhq.com/[PING_TOKEN]`.
	// +kubebuilder:validation:Optional
	PingToken *string `json:"pingToken,omitempty" tf:"ping_token,omitempty"`
}

type HeartbeatInitParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []HeartbeatAlertChannelSubscriptionInitParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []HeartbeatAlertSettingsInitParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set, Min: 1, Max: 1) (see below for nested schema)
	Heartbeat []HeartbeatHeartbeatInitParameters `json:"heartbeat,omitempty" tf:"heartbeat,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []HeartbeatTriggerIncidentInitParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type HeartbeatObservation struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []HeartbeatAlertChannelSubscriptionObservation `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []HeartbeatAlertSettingsObservation `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set, Min: 1, Max: 1) (see below for nested schema)
	Heartbeat []HeartbeatHeartbeatObservation `json:"heartbeat,omitempty" tf:"heartbeat,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []HeartbeatTriggerIncidentObservation `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type HeartbeatParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	// +kubebuilder:validation:Optional
	AlertChannelSubscription []HeartbeatAlertChannelSubscriptionParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	// +kubebuilder:validation:Optional
	AlertSettings []HeartbeatAlertSettingsParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set, Min: 1, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Heartbeat []HeartbeatHeartbeatParameters `json:"heartbeat,omitempty" tf:"heartbeat,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// +kubebuilder:validation:Optional
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	// +kubebuilder:validation:Optional
	TriggerIncident []HeartbeatTriggerIncidentParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	// +kubebuilder:validation:Optional
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type HeartbeatTriggerIncidentInitParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type HeartbeatTriggerIncidentObservation struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type HeartbeatTriggerIncidentParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	// +kubebuilder:validation:Optional
	NotifySubscribers *bool `json:"notifySubscribers" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity" tf:"severity,omitempty"`
}

// HeartbeatSpec defines the desired state of Heartbeat
type HeartbeatSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HeartbeatParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HeartbeatInitParameters `json:"initProvider,omitempty"`
}

// HeartbeatStatus defines the observed state of Heartbeat.
type HeartbeatStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HeartbeatObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Heartbeat is the Schema for the Heartbeats API. The checkly_heartbeat resource has been renamed to checkly_heartbeat_monitor to better reflect its position in the Checkly product lineup. We recommend using the checkly_heartbeat_monitor resource type for any new resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,checkly}
type Heartbeat struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.activated) || (has(self.initProvider) && has(self.initProvider.activated))",message="spec.forProvider.activated is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.heartbeat) || (has(self.initProvider) && has(self.initProvider.heartbeat))",message="spec.forProvider.heartbeat is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   HeartbeatSpec   `json:"spec"`
	Status HeartbeatStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HeartbeatList contains a list of Heartbeats
type HeartbeatList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Heartbeat `json:"items"`
}

// Repository type metadata.
var (
	Heartbeat_Kind             = "Heartbeat"
	Heartbeat_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Heartbeat_Kind}.String()
	Heartbeat_KindAPIVersion   = Heartbeat_Kind + "." + CRDGroupVersion.String()
	Heartbeat_GroupVersionKind = CRDGroupVersion.WithKind(Heartbeat_Kind)
)

func init() {
	SchemeBuilder.Register(&Heartbeat{}, &HeartbeatList{})
}
