// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PlaywrightCodeBundleInitParameters struct {

	// (Block List, Min: 1, Max: 1) A prebuilt archive containing the code bundle. (see below for nested schema)
	// A prebuilt archive containing the code bundle.
	PrebuiltArchive []PrebuiltArchiveInitParameters `json:"prebuiltArchive,omitempty" tf:"prebuilt_archive,omitempty"`
}

type PlaywrightCodeBundleObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// consumable and should be passed as-is to a Playwright check resource.
	// An opaque blob of generated metadata. The value is not intended to be user-consumable and should be passed as-is to a Playwright check resource.
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Block List, Min: 1, Max: 1) A prebuilt archive containing the code bundle. (see below for nested schema)
	// A prebuilt archive containing the code bundle.
	PrebuiltArchive []PrebuiltArchiveObservation `json:"prebuiltArchive,omitempty" tf:"prebuilt_archive,omitempty"`
}

type PlaywrightCodeBundleParameters struct {

	// (Block List, Min: 1, Max: 1) A prebuilt archive containing the code bundle. (see below for nested schema)
	// A prebuilt archive containing the code bundle.
	// +kubebuilder:validation:Optional
	PrebuiltArchive []PrebuiltArchiveParameters `json:"prebuiltArchive,omitempty" tf:"prebuilt_archive,omitempty"`
}

type PrebuiltArchiveInitParameters struct {

	// (String) Path to the archive file.
	// Path to the archive file.
	File *string `json:"file,omitempty" tf:"file,omitempty"`
}

type PrebuiltArchiveObservation struct {

	// (String) Path to the archive file.
	// Path to the archive file.
	File *string `json:"file,omitempty" tf:"file,omitempty"`
}

type PrebuiltArchiveParameters struct {

	// (String) Path to the archive file.
	// Path to the archive file.
	// +kubebuilder:validation:Optional
	File *string `json:"file" tf:"file,omitempty"`
}

// PlaywrightCodeBundleSpec defines the desired state of PlaywrightCodeBundle
type PlaywrightCodeBundleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PlaywrightCodeBundleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PlaywrightCodeBundleInitParameters `json:"initProvider,omitempty"`
}

// PlaywrightCodeBundleStatus defines the observed state of PlaywrightCodeBundle.
type PlaywrightCodeBundleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PlaywrightCodeBundleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PlaywrightCodeBundle is the Schema for the PlaywrightCodeBundles API. A managed code bundle which can be used in Playwright Check Suite resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,checkly}
type PlaywrightCodeBundle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.prebuiltArchive) || (has(self.initProvider) && has(self.initProvider.prebuiltArchive))",message="spec.forProvider.prebuiltArchive is a required parameter"
	Spec   PlaywrightCodeBundleSpec   `json:"spec"`
	Status PlaywrightCodeBundleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PlaywrightCodeBundleList contains a list of PlaywrightCodeBundles
type PlaywrightCodeBundleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PlaywrightCodeBundle `json:"items"`
}

// Repository type metadata.
var (
	PlaywrightCodeBundle_Kind             = "PlaywrightCodeBundle"
	PlaywrightCodeBundle_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PlaywrightCodeBundle_Kind}.String()
	PlaywrightCodeBundle_KindAPIVersion   = PlaywrightCodeBundle_Kind + "." + CRDGroupVersion.String()
	PlaywrightCodeBundle_GroupVersionKind = CRDGroupVersion.WithKind(PlaywrightCodeBundle_Kind)
)

func init() {
	SchemeBuilder.Register(&PlaywrightCodeBundle{}, &PlaywrightCodeBundleList{})
}
