apiVersion: playwright.checkly.m.crossplane.io/v1alpha1
kind: CheckSuite
metadata:
  annotations:
    meta.upbound.io/example-id: playwright/v1alpha1/checksuite
  labels:
    testing.upbound.io/example-name: example-playwright-check
  name: example-playwright-check
  namespace: upbound-system
spec:
  forProvider:
    activated: true
    bundle:
    - id: ${checkly_playwright_code_bundle.playwright-bundle.id}
      metadata: ${checkly_playwright_code_bundle.playwright-bundle.metadata}
    frequency: 2
    locations:
    - eu-west-1
    name: Example Playwright check
    useGlobalAlertSettings: true

---

apiVersion: checks.checkly.m.crossplane.io/v1alpha1
kind: PlaywrightCodeBundle
metadata:
  annotations:
    meta.upbound.io/example-id: playwright/v1alpha1/checksuite
  labels:
    testing.upbound.io/example-name: playwright-bundle
  name: playwright-bundle
  namespace: upbound-system
spec:
  forProvider:
    prebuiltArchive:
    - file: ${data.archive_file.playwright-bundle.output_path}
