apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - providerconfig.yaml
  - snippet.yaml
  - checks.yaml
labels:
  - pairs:
      managed-by: crossplane
      scenario: gitops-setup
