//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardInitParameters) DeepCopyInto(out *CardInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardInitParameters.
func (in *CardInitParameters) DeepCopy() *CardInitParameters {
	if in == nil {
		return nil
	}
	out := new(CardInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardObservation) DeepCopyInto(out *CardObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardObservation.
func (in *CardObservation) DeepCopy() *CardObservation {
	if in == nil {
		return nil
	}
	out := new(CardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardParameters) DeepCopyInto(out *CardParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardParameters.
func (in *CardParameters) DeepCopy() *CardParameters {
	if in == nil {
		return nil
	}
	out := new(CardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Page) DeepCopyInto(out *Page) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Page.
func (in *Page) DeepCopy() *Page {
	if in == nil {
		return nil
	}
	out := new(Page)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Page) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageInitParameters) DeepCopyInto(out *PageInitParameters) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageInitParameters.
func (in *PageInitParameters) DeepCopy() *PageInitParameters {
	if in == nil {
		return nil
	}
	out := new(PageInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageList) DeepCopyInto(out *PageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Page, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageList.
func (in *PageList) DeepCopy() *PageList {
	if in == nil {
		return nil
	}
	out := new(PageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageObservation) DeepCopyInto(out *PageObservation) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageObservation.
func (in *PageObservation) DeepCopy() *PageObservation {
	if in == nil {
		return nil
	}
	out := new(PageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageParameters) DeepCopyInto(out *PageParameters) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageParameters.
func (in *PageParameters) DeepCopy() *PageParameters {
	if in == nil {
		return nil
	}
	out := new(PageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageService) DeepCopyInto(out *PageService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageService.
func (in *PageService) DeepCopy() *PageService {
	if in == nil {
		return nil
	}
	out := new(PageService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PageService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceInitParameters) DeepCopyInto(out *PageServiceInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceInitParameters.
func (in *PageServiceInitParameters) DeepCopy() *PageServiceInitParameters {
	if in == nil {
		return nil
	}
	out := new(PageServiceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceList) DeepCopyInto(out *PageServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PageService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceList.
func (in *PageServiceList) DeepCopy() *PageServiceList {
	if in == nil {
		return nil
	}
	out := new(PageServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PageServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceObservation) DeepCopyInto(out *PageServiceObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceObservation.
func (in *PageServiceObservation) DeepCopy() *PageServiceObservation {
	if in == nil {
		return nil
	}
	out := new(PageServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceParameters) DeepCopyInto(out *PageServiceParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceParameters.
func (in *PageServiceParameters) DeepCopy() *PageServiceParameters {
	if in == nil {
		return nil
	}
	out := new(PageServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceSpec) DeepCopyInto(out *PageServiceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceSpec.
func (in *PageServiceSpec) DeepCopy() *PageServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PageServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageServiceStatus) DeepCopyInto(out *PageServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageServiceStatus.
func (in *PageServiceStatus) DeepCopy() *PageServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PageServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageSpec) DeepCopyInto(out *PageSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageSpec.
func (in *PageSpec) DeepCopy() *PageSpec {
	if in == nil {
		return nil
	}
	out := new(PageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageStatus) DeepCopyInto(out *PageStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageStatus.
func (in *PageStatus) DeepCopy() *PageStatus {
	if in == nil {
		return nil
	}
	out := new(PageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentInitParameters) DeepCopyInto(out *ServiceAttachmentInitParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentInitParameters.
func (in *ServiceAttachmentInitParameters) DeepCopy() *ServiceAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentObservation) DeepCopyInto(out *ServiceAttachmentObservation) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentObservation.
func (in *ServiceAttachmentObservation) DeepCopy() *ServiceAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentParameters) DeepCopyInto(out *ServiceAttachmentParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentParameters.
func (in *ServiceAttachmentParameters) DeepCopy() *ServiceAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}
