// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CardInitParameters struct {

	// (String) The name of the status page.
	// The name of the card.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Min: 1) A list of services to attach to the card. (see below for nested schema)
	// A list of services to attach to the card.
	ServiceAttachment []ServiceAttachmentInitParameters `json:"serviceAttachment,omitempty" tf:"service_attachment,omitempty"`
}

type CardObservation struct {

	// (String) The name of the status page.
	// The name of the card.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Min: 1) A list of services to attach to the card. (see below for nested schema)
	// A list of services to attach to the card.
	ServiceAttachment []ServiceAttachmentObservation `json:"serviceAttachment,omitempty" tf:"service_attachment,omitempty"`
}

type CardParameters struct {

	// (String) The name of the status page.
	// The name of the card.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Block List, Min: 1) A list of services to attach to the card. (see below for nested schema)
	// A list of services to attach to the card.
	// +kubebuilder:validation:Optional
	ServiceAttachment []ServiceAttachmentParameters `json:"serviceAttachment" tf:"service_attachment,omitempty"`
}

type PageInitParameters struct {

	// (Block List, Min: 1) A list of cards to include on the status page. (see below for nested schema)
	// A list of cards to include on the status page.
	Card []CardInitParameters `json:"card,omitempty" tf:"card,omitempty"`

	// (String) A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	// A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	CustomDomain *string `json:"customDomain,omitempty" tf:"custom_domain,omitempty"`

	// (String) Possible values are AUTO, DARK, and LIGHT. (Default AUTO).
	// Possible values are `AUTO`, `DARK`, and `LIGHT`. (Default `AUTO`).
	DefaultTheme *string `json:"defaultTheme,omitempty" tf:"default_theme,omitempty"`

	// (String) A URL to an image file to use as the favicon of the status page.
	// A URL to an image file to use as the favicon of the status page.
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) A URL to an image file to use as the logo for the status page.
	// A URL to an image file to use as the logo for the status page.
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL the user should be redirected to when clicking the logo.
	// The URL the user should be redirected to when clicking the logo.
	RedirectTo *string `json:"redirectTo,omitempty" tf:"redirect_to,omitempty"`

	// (String) The URL of the status page.
	// The URL of the status page.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type PageObservation struct {

	// (Block List, Min: 1) A list of cards to include on the status page. (see below for nested schema)
	// A list of cards to include on the status page.
	Card []CardObservation `json:"card,omitempty" tf:"card,omitempty"`

	// (String) A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	// A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	CustomDomain *string `json:"customDomain,omitempty" tf:"custom_domain,omitempty"`

	// (String) Possible values are AUTO, DARK, and LIGHT. (Default AUTO).
	// Possible values are `AUTO`, `DARK`, and `LIGHT`. (Default `AUTO`).
	DefaultTheme *string `json:"defaultTheme,omitempty" tf:"default_theme,omitempty"`

	// (String) A URL to an image file to use as the favicon of the status page.
	// A URL to an image file to use as the favicon of the status page.
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) A URL to an image file to use as the logo for the status page.
	// A URL to an image file to use as the logo for the status page.
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL the user should be redirected to when clicking the logo.
	// The URL the user should be redirected to when clicking the logo.
	RedirectTo *string `json:"redirectTo,omitempty" tf:"redirect_to,omitempty"`

	// (String) The URL of the status page.
	// The URL of the status page.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type PageParameters struct {

	// (Block List, Min: 1) A list of cards to include on the status page. (see below for nested schema)
	// A list of cards to include on the status page.
	// +kubebuilder:validation:Optional
	Card []CardParameters `json:"card,omitempty" tf:"card,omitempty"`

	// (String) A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	// A custom user domain, e.g. "status.example.com". See the docs on updating your DNS and SSL usage.
	// +kubebuilder:validation:Optional
	CustomDomain *string `json:"customDomain,omitempty" tf:"custom_domain,omitempty"`

	// (String) Possible values are AUTO, DARK, and LIGHT. (Default AUTO).
	// Possible values are `AUTO`, `DARK`, and `LIGHT`. (Default `AUTO`).
	// +kubebuilder:validation:Optional
	DefaultTheme *string `json:"defaultTheme,omitempty" tf:"default_theme,omitempty"`

	// (String) A URL to an image file to use as the favicon of the status page.
	// A URL to an image file to use as the favicon of the status page.
	// +kubebuilder:validation:Optional
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) A URL to an image file to use as the logo for the status page.
	// A URL to an image file to use as the logo for the status page.
	// +kubebuilder:validation:Optional
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL the user should be redirected to when clicking the logo.
	// The URL the user should be redirected to when clicking the logo.
	// +kubebuilder:validation:Optional
	RedirectTo *string `json:"redirectTo,omitempty" tf:"redirect_to,omitempty"`

	// (String) The URL of the status page.
	// The URL of the status page.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceAttachmentInitParameters struct {

	// (String) The ID of the service.
	// The ID of the service.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type ServiceAttachmentObservation struct {

	// (String) The ID of the service.
	// The ID of the service.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type ServiceAttachmentParameters struct {

	// (String) The ID of the service.
	// The ID of the service.
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId" tf:"service_id,omitempty"`
}

// PageSpec defines the desired state of Page
type PageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PageInitParameters `json:"initProvider,omitempty"`
}

// PageStatus defines the observed state of Page.
type PageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Page is the Schema for the Pages API. Checkly status pages allow you to easily communicate the uptime and health of your applications and services to your customers.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,checkly}
type Page struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.card) || (has(self.initProvider) && has(self.initProvider.card))",message="spec.forProvider.card is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   PageSpec   `json:"spec"`
	Status PageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PageList contains a list of Pages
type PageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Page `json:"items"`
}

// Repository type metadata.
var (
	Page_Kind             = "Page"
	Page_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Page_Kind}.String()
	Page_KindAPIVersion   = Page_Kind + "." + CRDGroupVersion.String()
	Page_GroupVersionKind = CRDGroupVersion.WithKind(Page_Kind)
)

func init() {
	SchemeBuilder.Register(&Page{}, &PageList{})
}
