apiVersion: checks.checkly.crossplane.io/v1alpha1
kind: PlaywrightCodeBundle
metadata:
  annotations:
    meta.upbound.io/example-id: checks/v1alpha1/playwrightcodebundle
  labels:
    testing.upbound.io/example-name: example-1
  name: example-1
spec:
  forProvider:
    prebuiltArchive:
    - file: ${data.archive_file.playwright-bundle.output_path}
