apiVersion: checks.checkly.crossplane.io/v1alpha1
kind: PlaywrightCheckSuite
metadata:
  annotations:
    meta.upbound.io/example-id: checks/v1alpha1/playwrightchecksuite
  labels:
    testing.upbound.io/example-name: example-playwright-check
  name: example-playwright-check
spec:
  forProvider:
    activated: true
    bundle:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: playwright-bundle
      metadata: ${checkly_playwright_code_bundle.playwright-bundle.metadata}
    frequency: 2
    locations:
    - eu-west-1
    name: Example Playwright check
    useGlobalAlertSettings: true

---

apiVersion: checks.checkly.crossplane.io/v1alpha1
kind: PlaywrightCodeBundle
metadata:
  annotations:
    meta.upbound.io/example-id: checks/v1alpha1/playwrightchecksuite
  labels:
    testing.upbound.io/example-name: playwright-bundle
  name: playwright-bundle
spec:
  forProvider:
    prebuiltArchive:
    - file: ${data.archive_file.playwright-bundle.output_path}
