apiVersion: checks.checkly.crossplane.io/v1alpha1
kind: ICMPMonitor
metadata:
  name: example-icmp-monitor
  namespace: default
  annotations:
    meta.upbound.io/example-id: checks/v1alpha1/icmpmonitor
spec:
  forProvider:
    name: example-icmp-monitor
    activated: true
    frequency: 5
    locations:
      - us-east-1
      - eu-west-1
    request:
      - hostname: 8.8.8.8
    tags:
      - managed-by-crossplane
  providerConfigRef:
    name: default
