apiVersion: checks.checkly.crossplane.io/v1alpha1
kind: PlaywrightCodeBundle
metadata:
  name: hello-world-bundle
  namespace: default
  annotations:
    meta.upbound.io/example-id: checks/v1alpha1/playwrightcodebundle
spec:
  forProvider:
    prebuiltArchive:
      - file: ./hello-world.tar.gz
  providerConfigRef:
    name: default
