// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/sanmoh-hombal/provider-checkly/apis/cluster/alerts/v1alpha1"
	v1alpha1checks "github.com/sanmoh-hombal/provider-checkly/apis/cluster/checks/v1alpha1"
	v1alpha1infra "github.com/sanmoh-hombal/provider-checkly/apis/cluster/infra/v1alpha1"
	v1alpha1statuspage "github.com/sanmoh-hombal/provider-checkly/apis/cluster/statuspage/v1alpha1"
	v1alpha1triggers "github.com/sanmoh-hombal/provider-checkly/apis/cluster/triggers/v1alpha1"
	v1alpha1cluster "github.com/sanmoh-hombal/provider-checkly/apis/cluster/v1alpha1"
	v1beta1 "github.com/sanmoh-hombal/provider-checkly/apis/cluster/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1checks.SchemeBuilder.AddToScheme,
		v1alpha1infra.SchemeBuilder.AddToScheme,
		v1alpha1statuspage.SchemeBuilder.AddToScheme,
		v1alpha1triggers.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
