apiVersion: infra.checkly.m.crossplane.io/v1alpha1
kind: EnvironmentVariable
metadata:
  name: api-base-url
  namespace: default
  annotations:
    meta.upbound.io/example-id: infra/v1alpha1/environmentvariable
    crossplane.io/external-name: API_BASE_URL
spec:
  forProvider:
    valueSecretRef:
      key: value
      name: envvar-api-base-url
    locked: false
  providerConfigRef:
    kind: ProviderConfig
    name: default
