// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-checkly/apis/namespaced/alerts/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-checkly/apis/namespaced/infra/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Check.
func (mg *Check) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this CheckGroup.
func (mg *CheckGroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this CheckGroupV2.
func (mg *CheckGroupV2) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.EnforceAlertSettings); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDRef,
				Selector:     mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDSelector,
				To: reference.To{
					List:    &v1alpha1.AlertChannelList{},
					Managed: &v1alpha1.AlertChannel{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID")
			}
			mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.EnforceLocations); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocations),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocationRefs,
			Selector:      mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocationsSelector,
			To: reference.To{
				List:    &v1alpha11.PrivateLocationList{},
				Managed: &v1alpha11.PrivateLocation{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocations")
		}
		mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.EnforceLocations[i3].PrivateLocationRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.SetupScript); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.SetupScript[i3].SnippetID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SetupScript[i3].SnippetIDRef,
			Selector:     mg.Spec.ForProvider.SetupScript[i3].SnippetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SnippetList{},
				Managed: &v1alpha11.Snippet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SetupScript[i3].SnippetID")
		}
		mg.Spec.ForProvider.SetupScript[i3].SnippetID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SetupScript[i3].SnippetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.TeardownScript); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.TeardownScript[i3].SnippetID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.TeardownScript[i3].SnippetIDRef,
			Selector:     mg.Spec.ForProvider.TeardownScript[i3].SnippetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SnippetList{},
				Managed: &v1alpha11.Snippet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.TeardownScript[i3].SnippetID")
		}
		mg.Spec.ForProvider.TeardownScript[i3].SnippetID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.TeardownScript[i3].SnippetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.EnforceAlertSettings); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription); i4++ {
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDRef,
				Selector:     mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDSelector,
				To: reference.To{
					List:    &v1alpha1.AlertChannelList{},
					Managed: &v1alpha1.AlertChannel{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID")
			}
			mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.EnforceAlertSettings[i3].AlertChannelSubscription[i4].ChannelIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.EnforceLocations); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocations),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocationRefs,
			Selector:      mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocationsSelector,
			To: reference.To{
				List:    &v1alpha11.PrivateLocationList{},
				Managed: &v1alpha11.PrivateLocation{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocations")
		}
		mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.EnforceLocations[i3].PrivateLocationRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SetupScript); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.SetupScript[i3].SnippetID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SetupScript[i3].SnippetIDRef,
			Selector:     mg.Spec.InitProvider.SetupScript[i3].SnippetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SnippetList{},
				Managed: &v1alpha11.Snippet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SetupScript[i3].SnippetID")
		}
		mg.Spec.InitProvider.SetupScript[i3].SnippetID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SetupScript[i3].SnippetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.TeardownScript); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.TeardownScript[i3].SnippetID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.TeardownScript[i3].SnippetIDRef,
			Selector:     mg.Spec.InitProvider.TeardownScript[i3].SnippetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SnippetList{},
				Managed: &v1alpha11.Snippet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.TeardownScript[i3].SnippetID")
		}
		mg.Spec.InitProvider.TeardownScript[i3].SnippetID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.TeardownScript[i3].SnippetIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this DNSMonitor.
func (mg *DNSMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Heartbeat.
func (mg *Heartbeat) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this HeartbeatMonitor.
func (mg *HeartbeatMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this ICMPMonitor.
func (mg *ICMPMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PlaywrightCheckSuite.
func (mg *PlaywrightCheckSuite) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Bundle); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Bundle[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Bundle[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Bundle[i3].IDSelector,
			To: reference.To{
				List:    &PlaywrightCodeBundleList{},
				Managed: &PlaywrightCodeBundle{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Bundle[i3].ID")
		}
		mg.Spec.ForProvider.Bundle[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Bundle[i3].IDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Bundle); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Bundle[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Bundle[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Bundle[i3].IDSelector,
			To: reference.To{
				List:    &PlaywrightCodeBundleList{},
				Managed: &PlaywrightCodeBundle{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Bundle[i3].ID")
		}
		mg.Spec.InitProvider.Bundle[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Bundle[i3].IDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this TCPCheck.
func (mg *TCPCheck) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this TCPMonitor.
func (mg *TCPMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this URLMonitor.
func (mg *URLMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupIDRef,
		Selector:     mg.Spec.ForProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupID")
	}
	mg.Spec.ForProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PrivateLocationRefs,
		Selector:      mg.Spec.ForProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrivateLocations")
	}
	mg.Spec.ForProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertChannelSubscription); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef,
			Selector:     mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDSelector,
			To: reference.To{
				List:    &v1alpha1.AlertChannelList{},
				Managed: &v1alpha1.AlertChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID")
		}
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelID = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlertChannelSubscription[i3].ChannelIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.GroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupIDRef,
		Selector:     mg.Spec.InitProvider.GroupIDSelector,
		To: reference.To{
			List:    &CheckGroupList{},
			Managed: &CheckGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupID")
	}
	mg.Spec.InitProvider.GroupID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrivateLocations),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PrivateLocationRefs,
		Selector:      mg.Spec.InitProvider.PrivateLocationsSelector,
		To: reference.To{
			List:    &v1alpha11.PrivateLocationList{},
			Managed: &v1alpha11.PrivateLocation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrivateLocations")
	}
	mg.Spec.InitProvider.PrivateLocations = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrivateLocationRefs = mrsp.ResolvedReferences

	return nil
}
