// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TCPCheckAlertChannelSubscriptionInitParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/alerts/v1alpha1.AlertChannel
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`
}

type TCPCheckAlertChannelSubscriptionObservation struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`
}

type TCPCheckAlertChannelSubscriptionParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Whether an alert should be sent to this channel.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/alerts/v1alpha1.AlertChannel
	// +kubebuilder:validation:Optional
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`
}

type TCPCheckAlertSettingsInitParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []TCPCheckAlertSettingsParallelRunFailureThresholdInitParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []TCPCheckAlertSettingsRemindersInitParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []TCPCheckAlertSettingsRunBasedEscalationInitParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []TCPCheckAlertSettingsTimeBasedEscalationInitParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type TCPCheckAlertSettingsObservation struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []TCPCheckAlertSettingsParallelRunFailureThresholdObservation `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []TCPCheckAlertSettingsRemindersObservation `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []TCPCheckAlertSettingsRunBasedEscalationObservation `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []TCPCheckAlertSettingsTimeBasedEscalationObservation `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type TCPCheckAlertSettingsParallelRunFailureThresholdInitParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type TCPCheckAlertSettingsParallelRunFailureThresholdObservation struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type TCPCheckAlertSettingsParallelRunFailureThresholdParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	// +kubebuilder:validation:Optional
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type TCPCheckAlertSettingsParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	// +kubebuilder:validation:Optional
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	// +kubebuilder:validation:Optional
	ParallelRunFailureThreshold []TCPCheckAlertSettingsParallelRunFailureThresholdParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	// +kubebuilder:validation:Optional
	Reminders []TCPCheckAlertSettingsRemindersParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	// +kubebuilder:validation:Optional
	RunBasedEscalation []TCPCheckAlertSettingsRunBasedEscalationParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	// +kubebuilder:validation:Optional
	TimeBasedEscalation []TCPCheckAlertSettingsTimeBasedEscalationParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type TCPCheckAlertSettingsRemindersInitParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type TCPCheckAlertSettingsRemindersObservation struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type TCPCheckAlertSettingsRemindersParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type TCPCheckAlertSettingsRunBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type TCPCheckAlertSettingsRunBasedEscalationObservation struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type TCPCheckAlertSettingsRunBasedEscalationParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	// +kubebuilder:validation:Optional
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type TCPCheckAlertSettingsTimeBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type TCPCheckAlertSettingsTimeBasedEscalationObservation struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type TCPCheckAlertSettingsTimeBasedEscalationParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type TCPCheckInitParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []TCPCheckAlertChannelSubscriptionInitParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []TCPCheckAlertSettingsInitParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default 4000).
	// The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default `4000`).
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The id of the check group this check is part of.
	// The id of the check group this check is part of.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/checks/v1alpha1.CheckGroup
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.NamespacedReference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.NamespacedSelector `json:"groupIdSelector,omitempty" tf:"-"`

	// (Number) The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	// The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// east-1"])
	// An array of one or more data center locations where to run the this check. (Default ["us-east-1"])
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default 5000).
	// The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default `5000`).
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// References to Location in private to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationRefs []v1.NamespacedReference `json:"privateLocationRefs,omitempty" tf:"-"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/private/v1alpha1.Location
	// +crossplane:generate:reference:refFieldName=PrivateLocationRefs
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// Selector for a list of Location in private to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationsSelector *v1.NamespacedSelector `json:"privateLocationsSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1, Max: 1) The parameters for the TCP connection. (see below for nested schema)
	// The parameters for the TCP connection.
	Request []TCPCheckRequestInitParameters `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy []TCPCheckRetryStrategyInitParameters `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin.
	// Determines if the check should run in all selected locations in parallel or round-robin.
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (String) The ID of the runtime to use for this check.
	// The ID of the runtime to use for this check.
	RuntimeID *string `json:"runtimeId,omitempty" tf:"runtime_id,omitempty"`

	// (Boolean) Allows to invert the behaviour of when a check is considered to fail.
	// Allows to invert the behaviour of when a check is considered to fail.
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []TCPCheckTriggerIncidentInitParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type TCPCheckObservation struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []TCPCheckAlertChannelSubscriptionObservation `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []TCPCheckAlertSettingsObservation `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default 4000).
	// The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default `4000`).
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The id of the check group this check is part of.
	// The id of the check group this check is part of.
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// (Number) The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	// The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// east-1"])
	// An array of one or more data center locations where to run the this check. (Default ["us-east-1"])
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default 5000).
	// The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default `5000`).
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// (Block Set, Min: 1, Max: 1) The parameters for the TCP connection. (see below for nested schema)
	// The parameters for the TCP connection.
	Request []TCPCheckRequestObservation `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy []TCPCheckRetryStrategyObservation `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin.
	// Determines if the check should run in all selected locations in parallel or round-robin.
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (String) The ID of the runtime to use for this check.
	// The ID of the runtime to use for this check.
	RuntimeID *string `json:"runtimeId,omitempty" tf:"runtime_id,omitempty"`

	// (Boolean) Allows to invert the behaviour of when a check is considered to fail.
	// Allows to invert the behaviour of when a check is considered to fail.
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []TCPCheckTriggerIncidentObservation `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type TCPCheckParameters struct {

	// (Boolean) Determines if the check is running or not. Possible values true, and false.
	// Determines if the check is running or not. Possible values `true`, and `false`.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	// +kubebuilder:validation:Optional
	AlertChannelSubscription []TCPCheckAlertChannelSubscriptionParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	// +kubebuilder:validation:Optional
	AlertSettings []TCPCheckAlertSettingsParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default 4000).
	// The response time in milliseconds starting from which a check should be considered degraded. Possible values are between 0 and 5000. (Default `4000`).
	// +kubebuilder:validation:Optional
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	// +kubebuilder:validation:Optional
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	// +kubebuilder:validation:Optional
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The id of the check group this check is part of.
	// The id of the check group this check is part of.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/checks/v1alpha1.CheckGroup
	// +kubebuilder:validation:Optional
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.NamespacedReference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.NamespacedSelector `json:"groupIdSelector,omitempty" tf:"-"`

	// (Number) The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	// The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
	// +kubebuilder:validation:Optional
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// east-1"])
	// An array of one or more data center locations where to run the this check. (Default ["us-east-1"])
	// +kubebuilder:validation:Optional
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default 5000).
	// The response time in milliseconds starting from which a check should be considered failing. Possible values are between 0 and 5000. (Default `5000`).
	// +kubebuilder:validation:Optional
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// Determines if any notifications will be sent out when a check fails/degrades/recovers.
	// +kubebuilder:validation:Optional
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the check.
	// The name of the check.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// References to Location in private to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationRefs []v1.NamespacedReference `json:"privateLocationRefs,omitempty" tf:"-"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +crossplane:generate:reference:type=github.com/sanmoh-hombal/provider-checkly/apis/namespaced/private/v1alpha1.Location
	// +crossplane:generate:reference:refFieldName=PrivateLocationRefs
	// +kubebuilder:validation:Optional
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// Selector for a list of Location in private to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationsSelector *v1.NamespacedSelector `json:"privateLocationsSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1, Max: 1) The parameters for the TCP connection. (see below for nested schema)
	// The parameters for the TCP connection.
	// +kubebuilder:validation:Optional
	Request []TCPCheckRequestParameters `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	// +kubebuilder:validation:Optional
	RetryStrategy []TCPCheckRetryStrategyParameters `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin.
	// Determines if the check should run in all selected locations in parallel or round-robin.
	// +kubebuilder:validation:Optional
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (String) The ID of the runtime to use for this check.
	// The ID of the runtime to use for this check.
	// +kubebuilder:validation:Optional
	RuntimeID *string `json:"runtimeId,omitempty" tf:"runtime_id,omitempty"`

	// (Boolean) Allows to invert the behaviour of when a check is considered to fail.
	// Allows to invert the behaviour of when a check is considered to fail.
	// +kubebuilder:validation:Optional
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks.
	// A list of tags for organizing and filtering checks.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	// +kubebuilder:validation:Optional
	TriggerIncident []TCPCheckTriggerIncidentParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this check.
	// When true, the account level alert settings will be used, not the alert setting defined on this check.
	// +kubebuilder:validation:Optional
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type TCPCheckRequestAssertionInitParameters struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, HAS_KEY, NOT_HAS_KEY, HAS_VALUE, NOT_HAS_VALUE, IS_EMPTY, NOT_EMPTY, GREATER_THAN, LESS_THAN, CONTAINS, NOT_CONTAINS, IS_NULL, and NOT_NULL.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `HAS_KEY`, `NOT_HAS_KEY`, `HAS_VALUE`, `NOT_HAS_VALUE`, `IS_EMPTY`, `NOT_EMPTY`, `GREATER_THAN`, `LESS_THAN`, `CONTAINS`, `NOT_CONTAINS`, `IS_NULL`, and `NOT_NULL`.
	Comparison *string `json:"comparison,omitempty" tf:"comparison,omitempty"`

	// (String)
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. Possible values are RESPONSE_DATA and RESPONSE_TIME.
	// The source of the asserted value. Possible values are `RESPONSE_DATA` and `RESPONSE_TIME`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String)
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type TCPCheckRequestAssertionObservation struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, HAS_KEY, NOT_HAS_KEY, HAS_VALUE, NOT_HAS_VALUE, IS_EMPTY, NOT_EMPTY, GREATER_THAN, LESS_THAN, CONTAINS, NOT_CONTAINS, IS_NULL, and NOT_NULL.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `HAS_KEY`, `NOT_HAS_KEY`, `HAS_VALUE`, `NOT_HAS_VALUE`, `IS_EMPTY`, `NOT_EMPTY`, `GREATER_THAN`, `LESS_THAN`, `CONTAINS`, `NOT_CONTAINS`, `IS_NULL`, and `NOT_NULL`.
	Comparison *string `json:"comparison,omitempty" tf:"comparison,omitempty"`

	// (String)
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. Possible values are RESPONSE_DATA and RESPONSE_TIME.
	// The source of the asserted value. Possible values are `RESPONSE_DATA` and `RESPONSE_TIME`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String)
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type TCPCheckRequestAssertionParameters struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, HAS_KEY, NOT_HAS_KEY, HAS_VALUE, NOT_HAS_VALUE, IS_EMPTY, NOT_EMPTY, GREATER_THAN, LESS_THAN, CONTAINS, NOT_CONTAINS, IS_NULL, and NOT_NULL.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `HAS_KEY`, `NOT_HAS_KEY`, `HAS_VALUE`, `NOT_HAS_VALUE`, `IS_EMPTY`, `NOT_EMPTY`, `GREATER_THAN`, `LESS_THAN`, `CONTAINS`, `NOT_CONTAINS`, `IS_NULL`, and `NOT_NULL`.
	// +kubebuilder:validation:Optional
	Comparison *string `json:"comparison" tf:"comparison,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. Possible values are RESPONSE_DATA and RESPONSE_TIME.
	// The source of the asserted value. Possible values are `RESPONSE_DATA` and `RESPONSE_TIME`.
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type TCPCheckRequestInitParameters struct {

	// (Block Set) A request can have multiple assertions. (see below for nested schema)
	// A request can have multiple assertions.
	Assertion []TCPCheckRequestAssertionInitParameters `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (String) The data to send to the target host.
	// The data to send to the target host.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) The hostname or IP to connect to. Do not include a scheme or a port in this value.
	// The hostname or IP to connect to. Do not include a scheme or a port in this value.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The IP family to use when executing the TCP check. The value can be either IPv4 or IPv6.
	// The IP family to use when executing the TCP check. The value can be either `IPv4` or `IPv6`.
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Number) The port number to connect to.
	// The port number to connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type TCPCheckRequestObservation struct {

	// (Block Set) A request can have multiple assertions. (see below for nested schema)
	// A request can have multiple assertions.
	Assertion []TCPCheckRequestAssertionObservation `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (String) The data to send to the target host.
	// The data to send to the target host.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) The hostname or IP to connect to. Do not include a scheme or a port in this value.
	// The hostname or IP to connect to. Do not include a scheme or a port in this value.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The IP family to use when executing the TCP check. The value can be either IPv4 or IPv6.
	// The IP family to use when executing the TCP check. The value can be either `IPv4` or `IPv6`.
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Number) The port number to connect to.
	// The port number to connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type TCPCheckRequestParameters struct {

	// (Block Set) A request can have multiple assertions. (see below for nested schema)
	// A request can have multiple assertions.
	// +kubebuilder:validation:Optional
	Assertion []TCPCheckRequestAssertionParameters `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (String) The data to send to the target host.
	// The data to send to the target host.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) The hostname or IP to connect to. Do not include a scheme or a port in this value.
	// The hostname or IP to connect to. Do not include a scheme or a port in this value.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname" tf:"hostname,omitempty"`

	// (String) The IP family to use when executing the TCP check. The value can be either IPv4 or IPv6.
	// The IP family to use when executing the TCP check. The value can be either `IPv4` or `IPv6`.
	// +kubebuilder:validation:Optional
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Number) The port number to connect to.
	// The port number to connect to.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`
}

type TCPCheckRetryStrategyInitParameters struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	OnlyOn []TCPCheckRetryStrategyOnlyOnInitParameters `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TCPCheckRetryStrategyObservation struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	OnlyOn []TCPCheckRetryStrategyOnlyOnParameters `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TCPCheckRetryStrategyOnlyOnInitParameters struct {
}

type TCPCheckRetryStrategyOnlyOnObservation struct {
}

type TCPCheckRetryStrategyOnlyOnParameters struct {
}

type TCPCheckRetryStrategyParameters struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	// +kubebuilder:validation:Optional
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	// +kubebuilder:validation:Optional
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	// +kubebuilder:validation:Optional
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	// +kubebuilder:validation:Optional
	OnlyOn []TCPCheckRetryStrategyOnlyOnParameters `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	// +kubebuilder:validation:Optional
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type TCPCheckTriggerIncidentInitParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type TCPCheckTriggerIncidentObservation struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type TCPCheckTriggerIncidentParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// (String) The name of the check.
	// The name of the incident.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	// +kubebuilder:validation:Optional
	NotifySubscribers *bool `json:"notifySubscribers" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity" tf:"severity,omitempty"`
}

// TCPCheckSpec defines the desired state of TCPCheck
type TCPCheckSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TCPCheckParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TCPCheckInitParameters `json:"initProvider,omitempty"`
}

// TCPCheckStatus defines the observed state of TCPCheck.
type TCPCheckStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TCPCheckObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TCPCheck is the Schema for the TCPChecks API. The checkly_tcp_check resource has been renamed to checkly_tcp_monitor to better reflect its position in the Checkly product lineup. We recommend using the checkly_tcp_monitor resource type for any new resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,checkly}
type TCPCheck struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.activated) || (has(self.initProvider) && has(self.initProvider.activated))",message="spec.forProvider.activated is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.frequency) || (has(self.initProvider) && has(self.initProvider.frequency))",message="spec.forProvider.frequency is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.request) || (has(self.initProvider) && has(self.initProvider.request))",message="spec.forProvider.request is a required parameter"
	Spec   TCPCheckSpec   `json:"spec"`
	Status TCPCheckStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TCPCheckList contains a list of TCPChecks
type TCPCheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TCPCheck `json:"items"`
}

// Repository type metadata.
var (
	TCPCheck_Kind             = "TCPCheck"
	TCPCheck_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TCPCheck_Kind}.String()
	TCPCheck_KindAPIVersion   = TCPCheck_Kind + "." + CRDGroupVersion.String()
	TCPCheck_GroupVersionKind = CRDGroupVersion.WithKind(TCPCheck_Kind)
)

func init() {
	SchemeBuilder.Register(&TCPCheck{}, &TCPCheckList{})
}
