// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type URLMonitorAlertChannelSubscriptionInitParameters struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/alerts/v1alpha1.AlertChannel
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`
}

type URLMonitorAlertChannelSubscriptionObservation struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Whether an alert should be sent to this channel.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`
}

type URLMonitorAlertChannelSubscriptionParameters struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Whether an alert should be sent to this channel.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated" tf:"activated,omitempty"`

	// (Number) The ID of the alert channel.
	// The ID of the alert channel.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/alerts/v1alpha1.AlertChannel
	// +kubebuilder:validation:Optional
	ChannelID *float64 `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a AlertChannel in alerts to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`
}

type URLMonitorAlertSettingsInitParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []URLMonitorAlertSettingsParallelRunFailureThresholdInitParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []URLMonitorAlertSettingsRemindersInitParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []URLMonitorAlertSettingsRunBasedEscalationInitParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []URLMonitorAlertSettingsTimeBasedEscalationInitParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type URLMonitorAlertSettingsObservation struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	ParallelRunFailureThreshold []URLMonitorAlertSettingsParallelRunFailureThresholdObservation `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	Reminders []URLMonitorAlertSettingsRemindersObservation `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	RunBasedEscalation []URLMonitorAlertSettingsRunBasedEscalationObservation `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	TimeBasedEscalation []URLMonitorAlertSettingsTimeBasedEscalationObservation `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type URLMonitorAlertSettingsParallelRunFailureThresholdInitParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type URLMonitorAlertSettingsParallelRunFailureThresholdObservation struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type URLMonitorAlertSettingsParallelRunFailureThresholdParameters struct {

	// (Boolean) Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default false).
	// Whether parallel run failure threshold is enabled. Only applies if the monitor is scheduled for multiple locations in parallel. (Default `false`).
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Percentage of runs that must fail to trigger alert. Possible values are 10, 20, 30, 40, 50, 60, 70, 80, 90, and 100. (Default 10).
	// Percentage of runs that must fail to trigger alert. Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90`, and `100`. (Default `10`).
	// +kubebuilder:validation:Optional
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`
}

type URLMonitorAlertSettingsParameters struct {

	// (String) Determines the type of escalation to use. Possible values are RUN_BASED and TIME_BASED. (Default RUN_BASED).
	// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
	// +kubebuilder:validation:Optional
	EscalationType *string `json:"escalationType,omitempty" tf:"escalation_type,omitempty"`

	// (Block List) Configuration for parallel run failure threshold. (see below for nested schema)
	// Configuration for parallel run failure threshold.
	// +kubebuilder:validation:Optional
	ParallelRunFailureThreshold []URLMonitorAlertSettingsParallelRunFailureThresholdParameters `json:"parallelRunFailureThreshold,omitempty" tf:"parallel_run_failure_threshold,omitempty"`

	// (Block List) Defines how often to send reminder notifications after initial alert. (see below for nested schema)
	// Defines how often to send reminder notifications after initial alert.
	// +kubebuilder:validation:Optional
	Reminders []URLMonitorAlertSettingsRemindersParameters `json:"reminders,omitempty" tf:"reminders,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for run-based escalation.
	// +kubebuilder:validation:Optional
	RunBasedEscalation []URLMonitorAlertSettingsRunBasedEscalationParameters `json:"runBasedEscalation,omitempty" tf:"run_based_escalation,omitempty"`

	// based escalation. (see below for nested schema)
	// Configuration for time-based escalation.
	// +kubebuilder:validation:Optional
	TimeBasedEscalation []URLMonitorAlertSettingsTimeBasedEscalationParameters `json:"timeBasedEscalation,omitempty" tf:"time_based_escalation,omitempty"`
}

type URLMonitorAlertSettingsRemindersInitParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type URLMonitorAlertSettingsRemindersObservation struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type URLMonitorAlertSettingsRemindersParameters struct {

	// (Number) Number of reminder notifications to send. Possible values are 0, 1, 2, 3, 4, 5, and 100000 (0 to disable, 100000 for unlimited). (Default 0).
	// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Number) Interval between reminder notifications in minutes. Possible values are 5, 10, 15, and 30. (Default 5).
	// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type URLMonitorAlertSettingsRunBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type URLMonitorAlertSettingsRunBasedEscalationObservation struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type URLMonitorAlertSettingsRunBasedEscalationParameters struct {

	// (Number) Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between 1 and 5. (Default 1).
	// Send an alert notification after the given number of consecutive monitor runs have failed. Possible values are between `1` and `5`. (Default `1`).
	// +kubebuilder:validation:Optional
	FailedRunThreshold *float64 `json:"failedRunThreshold,omitempty" tf:"failed_run_threshold,omitempty"`
}

type URLMonitorAlertSettingsTimeBasedEscalationInitParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type URLMonitorAlertSettingsTimeBasedEscalationObservation struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type URLMonitorAlertSettingsTimeBasedEscalationParameters struct {

	// (Number) Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are 5, 10, 15, and 30. (Default 5).
	// Send an alert notification after the monitor has been failing for the given amount of time (in minutes). Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
	// +kubebuilder:validation:Optional
	MinutesFailingThreshold *float64 `json:"minutesFailingThreshold,omitempty" tf:"minutes_failing_threshold,omitempty"`
}

type URLMonitorInitParameters struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []URLMonitorAlertChannelSubscriptionInitParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []URLMonitorAlertSettingsInitParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered degraded. Possible values are between 0 and 30000. (Default 3000).
	// The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `30000`. (Default `3000`).
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The ID of the check group that this monitor is part of.
	// The ID of the check group that this monitor is part of.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/checks/v1alpha1.CheckGroup
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.NamespacedReference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.NamespacedSelector `json:"groupIdSelector,omitempty" tf:"-"`

	// (Number) The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// (Set of String) An array of one or more data center locations where to run the this monitor.
	// An array of one or more data center locations where to run the this monitor.
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered failing. Possible values are between 0 and 30000. (Default 5000).
	// The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `30000`. (Default `5000`).
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default false).
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the monitor.
	// The name of the monitor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// References to PrivateLocation in infra to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationRefs []v1.NamespacedReference `json:"privateLocationRefs,omitempty" tf:"-"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/infra/v1alpha1.PrivateLocation
	// +crossplane:generate:reference:refFieldName=PrivateLocationRefs
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// Selector for a list of PrivateLocation in infra to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationsSelector *v1.NamespacedSelector `json:"privateLocationsSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1, Max: 1) The parameters of the HTTP request. (see below for nested schema)
	// The parameters of the HTTP request.
	Request []URLMonitorRequestInitParameters `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy []URLMonitorRetryStrategyInitParameters `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin. (Default false).
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (Boolean) Allows to invert the behaviour of when the monitor is considered to fail. (Default false).
	// Allows to invert the behaviour of when the monitor is considered to fail. (Default `false`).
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks and monitors.
	// A list of tags for organizing and filtering checks and monitors.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []URLMonitorTriggerIncidentInitParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default true).
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type URLMonitorObservation struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	AlertChannelSubscription []URLMonitorAlertChannelSubscriptionObservation `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	AlertSettings []URLMonitorAlertSettingsObservation `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered degraded. Possible values are between 0 and 30000. (Default 3000).
	// The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `30000`. (Default `3000`).
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The ID of the check group that this monitor is part of.
	// The ID of the check group that this monitor is part of.
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// (Number) The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) An array of one or more data center locations where to run the this monitor.
	// An array of one or more data center locations where to run the this monitor.
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered failing. Possible values are between 0 and 30000. (Default 5000).
	// The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `30000`. (Default `5000`).
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default false).
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the monitor.
	// The name of the monitor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// (Block Set, Min: 1, Max: 1) The parameters of the HTTP request. (see below for nested schema)
	// The parameters of the HTTP request.
	Request []URLMonitorRequestObservation `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy []URLMonitorRetryStrategyObservation `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin. (Default false).
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (Boolean) Allows to invert the behaviour of when the monitor is considered to fail. (Default false).
	// Allows to invert the behaviour of when the monitor is considered to fail. (Default `false`).
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks and monitors.
	// A list of tags for organizing and filtering checks and monitors.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident []URLMonitorTriggerIncidentObservation `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default true).
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type URLMonitorParameters struct {

	// (Boolean) Determines whether the monitor will run periodically or not after being deployed.
	// Determines whether the monitor will run periodically or not after being deployed.
	// +kubebuilder:validation:Optional
	Activated *bool `json:"activated,omitempty" tf:"activated,omitempty"`

	// (Block Set) An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing. (see below for nested schema)
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
	// +kubebuilder:validation:Optional
	AlertChannelSubscription []URLMonitorAlertChannelSubscriptionParameters `json:"alertChannelSubscription,omitempty" tf:"alert_channel_subscription,omitempty"`

	// (Block List, Max: 1) Determines the alert escalation policy for the monitor. (see below for nested schema)
	// Determines the alert escalation policy for the monitor.
	// +kubebuilder:validation:Optional
	AlertSettings []URLMonitorAlertSettingsParameters `json:"alertSettings,omitempty" tf:"alert_settings,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered degraded. Possible values are between 0 and 30000. (Default 3000).
	// The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `30000`. (Default `3000`).
	// +kubebuilder:validation:Optional
	DegradedResponseTime *float64 `json:"degradedResponseTime,omitempty" tf:"degraded_response_time,omitempty"`

	// (String) A description of the monitor.
	// A description of the monitor.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// use frequency_offset to define the actual frequency), 1 (1 minute), 2 (2 minutes), 5 (5 minutes), 10 (10 minutes), 15 (15 minutes), 30 (30 minutes), 60 (1 hour), 120 (2 hours), 180 (3 hours), 360 (6 hours), 720 (12 hours) and 1440 (24 hours).
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	// +kubebuilder:validation:Optional
	Frequency *float64 `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// use frequency to define the actual frequency), 10 (10 seconds), 20 (20 seconds) and 30 (30 seconds).
	// When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	// +kubebuilder:validation:Optional
	FrequencyOffset *float64 `json:"frequencyOffset,omitempty" tf:"frequency_offset,omitempty"`

	// (Number) The ID of the check group that this monitor is part of.
	// The ID of the check group that this monitor is part of.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/checks/v1alpha1.CheckGroup
	// +kubebuilder:validation:Optional
	GroupID *float64 `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.NamespacedReference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a CheckGroup in checks to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.NamespacedSelector `json:"groupIdSelector,omitempty" tf:"-"`

	// (Number) The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	// +kubebuilder:validation:Optional
	GroupOrder *float64 `json:"groupOrder,omitempty" tf:"group_order,omitempty"`

	// (Set of String) An array of one or more data center locations where to run the this monitor.
	// An array of one or more data center locations where to run the this monitor.
	// +kubebuilder:validation:Optional
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// (Number) The response time in milliseconds where the monitor should be considered failing. Possible values are between 0 and 30000. (Default 5000).
	// The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `30000`. (Default `5000`).
	// +kubebuilder:validation:Optional
	MaxResponseTime *float64 `json:"maxResponseTime,omitempty" tf:"max_response_time,omitempty"`

	// (Boolean) Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default false).
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	// +kubebuilder:validation:Optional
	Muted *bool `json:"muted,omitempty" tf:"muted,omitempty"`

	// (String) The name of the monitor.
	// The name of the monitor.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// References to PrivateLocation in infra to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationRefs []v1.NamespacedReference `json:"privateLocationRefs,omitempty" tf:"-"`

	// (Set of String) An array of one or more private locations slugs.
	// An array of one or more private locations slugs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-checkly/apis/namespaced/infra/v1alpha1.PrivateLocation
	// +crossplane:generate:reference:refFieldName=PrivateLocationRefs
	// +kubebuilder:validation:Optional
	// +listType=set
	PrivateLocations []*string `json:"privateLocations,omitempty" tf:"private_locations,omitempty"`

	// Selector for a list of PrivateLocation in infra to populate privateLocations.
	// +kubebuilder:validation:Optional
	PrivateLocationsSelector *v1.NamespacedSelector `json:"privateLocationsSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1, Max: 1) The parameters of the HTTP request. (see below for nested schema)
	// The parameters of the HTTP request.
	// +kubebuilder:validation:Optional
	Request []URLMonitorRequestParameters `json:"request,omitempty" tf:"request,omitempty"`

	// (Block List, Max: 1) A strategy for retrying failed check/monitor runs. (see below for nested schema)
	// A strategy for retrying failed check/monitor runs.
	// +kubebuilder:validation:Optional
	RetryStrategy []URLMonitorRetryStrategyParameters `json:"retryStrategy,omitempty" tf:"retry_strategy,omitempty"`

	// robin. (Default false).
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	// +kubebuilder:validation:Optional
	RunParallel *bool `json:"runParallel,omitempty" tf:"run_parallel,omitempty"`

	// (Boolean) Allows to invert the behaviour of when the monitor is considered to fail. (Default false).
	// Allows to invert the behaviour of when the monitor is considered to fail. (Default `false`).
	// +kubebuilder:validation:Optional
	ShouldFail *bool `json:"shouldFail,omitempty" tf:"should_fail,omitempty"`

	// (Set of String) A list of tags for organizing and filtering checks and monitors.
	// A list of tags for organizing and filtering checks and monitors.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Block Set, Max: 1) Create and resolve an incident based on the alert configuration. Useful for status page automation. (see below for nested schema)
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	// +kubebuilder:validation:Optional
	TriggerIncident []URLMonitorTriggerIncidentParameters `json:"triggerIncident,omitempty" tf:"trigger_incident,omitempty"`

	// (Boolean) When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default true).
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	// +kubebuilder:validation:Optional
	UseGlobalAlertSettings *bool `json:"useGlobalAlertSettings,omitempty" tf:"use_global_alert_settings,omitempty"`
}

type URLMonitorRequestAssertionInitParameters struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, GREATER_THAN and LESS_THAN.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `GREATER_THAN` and `LESS_THAN`.
	Comparison *string `json:"comparison,omitempty" tf:"comparison,omitempty"`

	// (String)
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. The only allowed value is STATUS_CODE.
	// The source of the asserted value. The only allowed value is `STATUS_CODE`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) The target value. Typically 200 when the source is STATUS_CODE.
	// The target value. Typically `200` when the source is `STATUS_CODE`.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type URLMonitorRequestAssertionObservation struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, GREATER_THAN and LESS_THAN.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `GREATER_THAN` and `LESS_THAN`.
	Comparison *string `json:"comparison,omitempty" tf:"comparison,omitempty"`

	// (String)
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. The only allowed value is STATUS_CODE.
	// The source of the asserted value. The only allowed value is `STATUS_CODE`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) The target value. Typically 200 when the source is STATUS_CODE.
	// The target value. Typically `200` when the source is `STATUS_CODE`.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type URLMonitorRequestAssertionParameters struct {

	// (String) The type of comparison to be executed between expected and actual value of the assertion. Possible values are EQUALS, NOT_EQUALS, GREATER_THAN and LESS_THAN.
	// The type of comparison to be executed between expected and actual value of the assertion. Possible values are `EQUALS`, `NOT_EQUALS`, `GREATER_THAN` and `LESS_THAN`.
	// +kubebuilder:validation:Optional
	Comparison *string `json:"comparison" tf:"comparison,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Property *string `json:"property,omitempty" tf:"property,omitempty"`

	// (String) The source of the asserted value. The only allowed value is STATUS_CODE.
	// The source of the asserted value. The only allowed value is `STATUS_CODE`.
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`

	// (String) The target value. Typically 200 when the source is STATUS_CODE.
	// The target value. Typically `200` when the source is `STATUS_CODE`.
	// +kubebuilder:validation:Optional
	Target *string `json:"target" tf:"target,omitempty"`
}

type URLMonitorRequestInitParameters struct {

	// (Block Set) Assertions to validate the HTTP response. URL monitors only support status code assertions. (see below for nested schema)
	// Assertions to validate the HTTP response. URL monitors only support status code assertions.
	Assertion []URLMonitorRequestAssertionInitParameters `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (Boolean) Whether to follow HTTP redirects automatically. (Default true).
	// Whether to follow HTTP redirects automatically. (Default `true`).
	FollowRedirects *bool `json:"followRedirects,omitempty" tf:"follow_redirects,omitempty"`

	// (String) IP family version to use for the connection. The value can be either IPv4 or IPv6. (Default IPv4).
	// IP family version to use for the connection. The value can be either `IPv4` or `IPv6`. (Default `IPv4`).
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Boolean) Whether to skip SSL certificate verification. (Default false).
	// Whether to skip SSL certificate verification. (Default `false`).
	SkipSSL *bool `json:"skipSsl,omitempty" tf:"skip_ssl,omitempty"`

	// (String) The URL to monitor. Must be a valid HTTP or HTTPS URL.
	// The URL to monitor. Must be a valid HTTP or HTTPS URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type URLMonitorRequestObservation struct {

	// (Block Set) Assertions to validate the HTTP response. URL monitors only support status code assertions. (see below for nested schema)
	// Assertions to validate the HTTP response. URL monitors only support status code assertions.
	Assertion []URLMonitorRequestAssertionObservation `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (Boolean) Whether to follow HTTP redirects automatically. (Default true).
	// Whether to follow HTTP redirects automatically. (Default `true`).
	FollowRedirects *bool `json:"followRedirects,omitempty" tf:"follow_redirects,omitempty"`

	// (String) IP family version to use for the connection. The value can be either IPv4 or IPv6. (Default IPv4).
	// IP family version to use for the connection. The value can be either `IPv4` or `IPv6`. (Default `IPv4`).
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Boolean) Whether to skip SSL certificate verification. (Default false).
	// Whether to skip SSL certificate verification. (Default `false`).
	SkipSSL *bool `json:"skipSsl,omitempty" tf:"skip_ssl,omitempty"`

	// (String) The URL to monitor. Must be a valid HTTP or HTTPS URL.
	// The URL to monitor. Must be a valid HTTP or HTTPS URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type URLMonitorRequestParameters struct {

	// (Block Set) Assertions to validate the HTTP response. URL monitors only support status code assertions. (see below for nested schema)
	// Assertions to validate the HTTP response. URL monitors only support status code assertions.
	// +kubebuilder:validation:Optional
	Assertion []URLMonitorRequestAssertionParameters `json:"assertion,omitempty" tf:"assertion,omitempty"`

	// (Boolean) Whether to follow HTTP redirects automatically. (Default true).
	// Whether to follow HTTP redirects automatically. (Default `true`).
	// +kubebuilder:validation:Optional
	FollowRedirects *bool `json:"followRedirects,omitempty" tf:"follow_redirects,omitempty"`

	// (String) IP family version to use for the connection. The value can be either IPv4 or IPv6. (Default IPv4).
	// IP family version to use for the connection. The value can be either `IPv4` or `IPv6`. (Default `IPv4`).
	// +kubebuilder:validation:Optional
	IPFamily *string `json:"ipFamily,omitempty" tf:"ip_family,omitempty"`

	// (Boolean) Whether to skip SSL certificate verification. (Default false).
	// Whether to skip SSL certificate verification. (Default `false`).
	// +kubebuilder:validation:Optional
	SkipSSL *bool `json:"skipSsl,omitempty" tf:"skip_ssl,omitempty"`

	// (String) The URL to monitor. Must be a valid HTTP or HTTPS URL.
	// The URL to monitor. Must be a valid HTTP or HTTPS URL.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type URLMonitorRetryStrategyInitParameters struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	OnlyOn []URLMonitorRetryStrategyOnlyOnInitParameters `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type URLMonitorRetryStrategyObservation struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	OnlyOn []URLMonitorRetryStrategyOnlyOnObservation `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type URLMonitorRetryStrategyOnlyOnInitParameters struct {

	// (Boolean) When true, retry only if the cause of the failure is a network error. (Default false).
	// When `true`, retry only if the cause of the failure is a network error. (Default `false`).
	NetworkError *bool `json:"networkError,omitempty" tf:"network_error,omitempty"`
}

type URLMonitorRetryStrategyOnlyOnObservation struct {

	// (Boolean) When true, retry only if the cause of the failure is a network error. (Default false).
	// When `true`, retry only if the cause of the failure is a network error. (Default `false`).
	NetworkError *bool `json:"networkError,omitempty" tf:"network_error,omitempty"`
}

type URLMonitorRetryStrategyOnlyOnParameters struct {

	// (Boolean) When true, retry only if the cause of the failure is a network error. (Default false).
	// When `true`, retry only if the cause of the failure is a network error. (Default `false`).
	// +kubebuilder:validation:Optional
	NetworkError *bool `json:"networkError,omitempty" tf:"network_error,omitempty"`
}

type URLMonitorRetryStrategyParameters struct {

	// (Number) The number of seconds to wait before the first retry attempt. (Default 60).
	// The number of seconds to wait before the first retry attempt. (Default `60`).
	// +kubebuilder:validation:Optional
	BaseBackoffSeconds *float64 `json:"baseBackoffSeconds,omitempty" tf:"base_backoff_seconds,omitempty"`

	// (Number) The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 600).
	// The total amount of time to continue retrying the check/monitor (maximum 600 seconds). Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `600`).
	// +kubebuilder:validation:Optional
	MaxDurationSeconds *float64 `json:"maxDurationSeconds,omitempty" tf:"max_duration_seconds,omitempty"`

	// (Number) The maximum number of times to retry the check/monitor. Value must be between 1 and 10. Available when type is FIXED, LINEAR, or EXPONENTIAL. (Default 2).
	// The maximum number of times to retry the check/monitor. Value must be between `1` and `10`. Available when `type` is `FIXED`, `LINEAR`, or `EXPONENTIAL`. (Default `2`).
	// +kubebuilder:validation:Optional
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// (Block List, Max: 1) Apply the retry strategy only if the defined conditions match. (see below for nested schema)
	// Apply the retry strategy only if the defined conditions match.
	// +kubebuilder:validation:Optional
	OnlyOn []URLMonitorRetryStrategyOnlyOnParameters `json:"onlyOn,omitempty" tf:"only_on,omitempty"`

	// (Boolean) Whether retries should be run in the same region as the initial check/monitor run. (Default true).
	// Whether retries should be run in the same region as the initial check/monitor run. (Default `true`).
	// +kubebuilder:validation:Optional
	SameRegion *bool `json:"sameRegion,omitempty" tf:"same_region,omitempty"`

	// (String) Determines which type of retry strategy to use. Possible values are FIXED, LINEAR, EXPONENTIAL, SINGLE_RETRY, and NO_RETRIES.
	// Determines which type of retry strategy to use. Possible values are `FIXED`, `LINEAR`, `EXPONENTIAL`, `SINGLE_RETRY`, and `NO_RETRIES`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type URLMonitorTriggerIncidentInitParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the monitor.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type URLMonitorTriggerIncidentObservation struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the monitor.
	// The name of the incident.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	NotifySubscribers *bool `json:"notifySubscribers,omitempty" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`
}

type URLMonitorTriggerIncidentParameters struct {

	// (String) A description of the monitor.
	// A detailed description of the incident.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// (String) The name of the monitor.
	// The name of the incident.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Boolean) Whether to notify subscribers when the incident is triggered.
	// Whether to notify subscribers when the incident is triggered.
	// +kubebuilder:validation:Optional
	NotifySubscribers *bool `json:"notifySubscribers" tf:"notify_subscribers,omitempty"`

	// (String) The status page service that this incident will be associated with.
	// The status page service that this incident will be associated with.
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId" tf:"service_id,omitempty"`

	// (String) The severity level of the incident. Possible values are MINOR, MEDIUM, MAJOR, and CRITICAL.
	// The severity level of the incident. Possible values are `MINOR`, `MEDIUM`, `MAJOR`, and `CRITICAL`.
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity" tf:"severity,omitempty"`
}

// URLMonitorSpec defines the desired state of URLMonitor
type URLMonitorSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            URLMonitorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider URLMonitorInitParameters `json:"initProvider,omitempty"`
}

// URLMonitorStatus defines the observed state of URLMonitor.
type URLMonitorStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        URLMonitorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// URLMonitor is the Schema for the URLMonitors API. Creates a URL Monitor to check HTTP endpoint availability and response times.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,checkly}
type URLMonitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.activated) || (has(self.initProvider) && has(self.initProvider.activated))",message="spec.forProvider.activated is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.frequency) || (has(self.initProvider) && has(self.initProvider.frequency))",message="spec.forProvider.frequency is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.request) || (has(self.initProvider) && has(self.initProvider.request))",message="spec.forProvider.request is a required parameter"
	Spec   URLMonitorSpec   `json:"spec"`
	Status URLMonitorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// URLMonitorList contains a list of URLMonitors
type URLMonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []URLMonitor `json:"items"`
}

// Repository type metadata.
var (
	URLMonitor_Kind             = "URLMonitor"
	URLMonitor_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: URLMonitor_Kind}.String()
	URLMonitor_KindAPIVersion   = URLMonitor_Kind + "." + CRDGroupVersion.String()
	URLMonitor_GroupVersionKind = CRDGroupVersion.WithKind(URLMonitor_Kind)
)

func init() {
	SchemeBuilder.Register(&URLMonitor{}, &URLMonitorList{})
}
