//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardInitParameters) DeepCopyInto(out *CardInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardInitParameters.
func (in *CardInitParameters) DeepCopy() *CardInitParameters {
	if in == nil {
		return nil
	}
	out := new(CardInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardObservation) DeepCopyInto(out *CardObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardObservation.
func (in *CardObservation) DeepCopy() *CardObservation {
	if in == nil {
		return nil
	}
	out := new(CardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardParameters) DeepCopyInto(out *CardParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = make([]ServiceAttachmentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardParameters.
func (in *CardParameters) DeepCopy() *CardParameters {
	if in == nil {
		return nil
	}
	out := new(CardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardInitParameters) DeepCopyInto(out *DashboardInitParameters) {
	*out = *in
	if in.ChecksPerPage != nil {
		in, out := &in.ChecksPerPage, &out.ChecksPerPage
		*out = new(float64)
		**out = **in
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.CustomURL != nil {
		in, out := &in.CustomURL, &out.CustomURL
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIncidents != nil {
		in, out := &in.EnableIncidents, &out.EnableIncidents
		*out = new(bool)
		**out = **in
	}
	if in.ExpandChecks != nil {
		in, out := &in.ExpandChecks, &out.ExpandChecks
		*out = new(bool)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(string)
		**out = **in
	}
	if in.HideTags != nil {
		in, out := &in.HideTags, &out.HideTags
		*out = new(bool)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Paginate != nil {
		in, out := &in.Paginate, &out.Paginate
		*out = new(bool)
		**out = **in
	}
	if in.PaginationRate != nil {
		in, out := &in.PaginationRate, &out.PaginationRate
		*out = new(float64)
		**out = **in
	}
	if in.RefreshRate != nil {
		in, out := &in.RefreshRate, &out.RefreshRate
		*out = new(float64)
		**out = **in
	}
	if in.ShowCheckRunLinks != nil {
		in, out := &in.ShowCheckRunLinks, &out.ShowCheckRunLinks
		*out = new(bool)
		**out = **in
	}
	if in.ShowHeader != nil {
		in, out := &in.ShowHeader, &out.ShowHeader
		*out = new(bool)
		**out = **in
	}
	if in.ShowP95 != nil {
		in, out := &in.ShowP95, &out.ShowP95
		*out = new(bool)
		**out = **in
	}
	if in.ShowP99 != nil {
		in, out := &in.ShowP99, &out.ShowP99
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseTagsAndOperator != nil {
		in, out := &in.UseTagsAndOperator, &out.UseTagsAndOperator
		*out = new(bool)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardInitParameters.
func (in *DashboardInitParameters) DeepCopy() *DashboardInitParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardList) DeepCopyInto(out *DashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardList.
func (in *DashboardList) DeepCopy() *DashboardList {
	if in == nil {
		return nil
	}
	out := new(DashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardObservation) DeepCopyInto(out *DashboardObservation) {
	*out = *in
	if in.ChecksPerPage != nil {
		in, out := &in.ChecksPerPage, &out.ChecksPerPage
		*out = new(float64)
		**out = **in
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.CustomURL != nil {
		in, out := &in.CustomURL, &out.CustomURL
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIncidents != nil {
		in, out := &in.EnableIncidents, &out.EnableIncidents
		*out = new(bool)
		**out = **in
	}
	if in.ExpandChecks != nil {
		in, out := &in.ExpandChecks, &out.ExpandChecks
		*out = new(bool)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(string)
		**out = **in
	}
	if in.HideTags != nil {
		in, out := &in.HideTags, &out.HideTags
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Paginate != nil {
		in, out := &in.Paginate, &out.Paginate
		*out = new(bool)
		**out = **in
	}
	if in.PaginationRate != nil {
		in, out := &in.PaginationRate, &out.PaginationRate
		*out = new(float64)
		**out = **in
	}
	if in.RefreshRate != nil {
		in, out := &in.RefreshRate, &out.RefreshRate
		*out = new(float64)
		**out = **in
	}
	if in.ShowCheckRunLinks != nil {
		in, out := &in.ShowCheckRunLinks, &out.ShowCheckRunLinks
		*out = new(bool)
		**out = **in
	}
	if in.ShowHeader != nil {
		in, out := &in.ShowHeader, &out.ShowHeader
		*out = new(bool)
		**out = **in
	}
	if in.ShowP95 != nil {
		in, out := &in.ShowP95, &out.ShowP95
		*out = new(bool)
		**out = **in
	}
	if in.ShowP99 != nil {
		in, out := &in.ShowP99, &out.ShowP99
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseTagsAndOperator != nil {
		in, out := &in.UseTagsAndOperator, &out.UseTagsAndOperator
		*out = new(bool)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardObservation.
func (in *DashboardObservation) DeepCopy() *DashboardObservation {
	if in == nil {
		return nil
	}
	out := new(DashboardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardParameters) DeepCopyInto(out *DashboardParameters) {
	*out = *in
	if in.ChecksPerPage != nil {
		in, out := &in.ChecksPerPage, &out.ChecksPerPage
		*out = new(float64)
		**out = **in
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.CustomURL != nil {
		in, out := &in.CustomURL, &out.CustomURL
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIncidents != nil {
		in, out := &in.EnableIncidents, &out.EnableIncidents
		*out = new(bool)
		**out = **in
	}
	if in.ExpandChecks != nil {
		in, out := &in.ExpandChecks, &out.ExpandChecks
		*out = new(bool)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(string)
		**out = **in
	}
	if in.HideTags != nil {
		in, out := &in.HideTags, &out.HideTags
		*out = new(bool)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Paginate != nil {
		in, out := &in.Paginate, &out.Paginate
		*out = new(bool)
		**out = **in
	}
	if in.PaginationRate != nil {
		in, out := &in.PaginationRate, &out.PaginationRate
		*out = new(float64)
		**out = **in
	}
	if in.RefreshRate != nil {
		in, out := &in.RefreshRate, &out.RefreshRate
		*out = new(float64)
		**out = **in
	}
	if in.ShowCheckRunLinks != nil {
		in, out := &in.ShowCheckRunLinks, &out.ShowCheckRunLinks
		*out = new(bool)
		**out = **in
	}
	if in.ShowHeader != nil {
		in, out := &in.ShowHeader, &out.ShowHeader
		*out = new(bool)
		**out = **in
	}
	if in.ShowP95 != nil {
		in, out := &in.ShowP95, &out.ShowP95
		*out = new(bool)
		**out = **in
	}
	if in.ShowP99 != nil {
		in, out := &in.ShowP99, &out.ShowP99
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseTagsAndOperator != nil {
		in, out := &in.UseTagsAndOperator, &out.UseTagsAndOperator
		*out = new(bool)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardParameters.
func (in *DashboardParameters) DeepCopy() *DashboardParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentInitParameters) DeepCopyInto(out *ServiceAttachmentInitParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentInitParameters.
func (in *ServiceAttachmentInitParameters) DeepCopy() *ServiceAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentObservation) DeepCopyInto(out *ServiceAttachmentObservation) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentObservation.
func (in *ServiceAttachmentObservation) DeepCopy() *ServiceAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentParameters) DeepCopyInto(out *ServiceAttachmentParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentParameters.
func (in *ServiceAttachmentParameters) DeepCopy() *ServiceAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPage) DeepCopyInto(out *StatusPage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPage.
func (in *StatusPage) DeepCopy() *StatusPage {
	if in == nil {
		return nil
	}
	out := new(StatusPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatusPage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageInitParameters) DeepCopyInto(out *StatusPageInitParameters) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageInitParameters.
func (in *StatusPageInitParameters) DeepCopy() *StatusPageInitParameters {
	if in == nil {
		return nil
	}
	out := new(StatusPageInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageList) DeepCopyInto(out *StatusPageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatusPage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageList.
func (in *StatusPageList) DeepCopy() *StatusPageList {
	if in == nil {
		return nil
	}
	out := new(StatusPageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatusPageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageObservation) DeepCopyInto(out *StatusPageObservation) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageObservation.
func (in *StatusPageObservation) DeepCopy() *StatusPageObservation {
	if in == nil {
		return nil
	}
	out := new(StatusPageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageParameters) DeepCopyInto(out *StatusPageParameters) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = make([]CardParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(string)
		**out = **in
	}
	if in.DefaultTheme != nil {
		in, out := &in.DefaultTheme, &out.DefaultTheme
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageParameters.
func (in *StatusPageParameters) DeepCopy() *StatusPageParameters {
	if in == nil {
		return nil
	}
	out := new(StatusPageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageService) DeepCopyInto(out *StatusPageService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageService.
func (in *StatusPageService) DeepCopy() *StatusPageService {
	if in == nil {
		return nil
	}
	out := new(StatusPageService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatusPageService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceInitParameters) DeepCopyInto(out *StatusPageServiceInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceInitParameters.
func (in *StatusPageServiceInitParameters) DeepCopy() *StatusPageServiceInitParameters {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceList) DeepCopyInto(out *StatusPageServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatusPageService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceList.
func (in *StatusPageServiceList) DeepCopy() *StatusPageServiceList {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatusPageServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceObservation) DeepCopyInto(out *StatusPageServiceObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StatusPageID != nil {
		in, out := &in.StatusPageID, &out.StatusPageID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceObservation.
func (in *StatusPageServiceObservation) DeepCopy() *StatusPageServiceObservation {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceParameters) DeepCopyInto(out *StatusPageServiceParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StatusPageID != nil {
		in, out := &in.StatusPageID, &out.StatusPageID
		*out = new(string)
		**out = **in
	}
	if in.StatusPageIDRef != nil {
		in, out := &in.StatusPageIDRef, &out.StatusPageIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusPageIDSelector != nil {
		in, out := &in.StatusPageIDSelector, &out.StatusPageIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceParameters.
func (in *StatusPageServiceParameters) DeepCopy() *StatusPageServiceParameters {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceSpec) DeepCopyInto(out *StatusPageServiceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceSpec.
func (in *StatusPageServiceSpec) DeepCopy() *StatusPageServiceSpec {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageServiceStatus) DeepCopyInto(out *StatusPageServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageServiceStatus.
func (in *StatusPageServiceStatus) DeepCopy() *StatusPageServiceStatus {
	if in == nil {
		return nil
	}
	out := new(StatusPageServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageSpec) DeepCopyInto(out *StatusPageSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageSpec.
func (in *StatusPageSpec) DeepCopy() *StatusPageSpec {
	if in == nil {
		return nil
	}
	out := new(StatusPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPageStatus) DeepCopyInto(out *StatusPageStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPageStatus.
func (in *StatusPageStatus) DeepCopy() *StatusPageStatus {
	if in == nil {
		return nil
	}
	out := new(StatusPageStatus)
	in.DeepCopyInto(out)
	return out
}
