apiVersion: client.checkly.m.crossplane.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    certificate: ${file("${path.module}/cert.pem")}
    host: '*.acme.com'
    passphraseSecretRef:
      key: example-key
      name: example-secret
    privateKey: ${file("${path.module}/key.pem")}
    trustedCa: ${file("${path.module}/ca.pem")}
